title: Vishesh Dembla
email: visheshdembla@hotmail.com
description: >- 
  Personal Blog And Portfolio
baseurl: "" 
url: "visheshdembla.co" 
twitter_username: visheshsays
github_username:  vishesh-dembla

# Build settings
markdown: kramdown
remote_theme: yous/whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
